// <auto-generated />
using System;
using DatabaseApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250611203127_FinalMigration")]
    partial class FinalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DatabaseApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RequiredCertifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DatabaseApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedSaleTerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusSalaryUsd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlySalaryUsd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSaleTerminalId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasDiscriminator().HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DatabaseApp.Models.PaymentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTimeOfPayment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SaleTerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleTerminalId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("DatabaseApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PriceUsd")
                        .HasColumnType("REAL");

                    b.Property<float>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDetailsId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DatabaseApp.Models.SaleTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaleTerminals");
                });

            modelBuilder.Entity("DatabaseApp.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Employee");

                    b.Property<bool>("WorksNightShift")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("FullTimeEmployee");
                });

            modelBuilder.Entity("DatabaseApp.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Employee");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("PartTimeEmployee");
                });

            modelBuilder.Entity("DatabaseApp.Models.Food", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Product");

                    b.Property<int>("CalorieCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("DatabaseApp.Models.Furniture", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Product");

                    b.Property<int>("HeightCm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WidthCm")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Furniture");
                });

            modelBuilder.Entity("DatabaseApp.Models.Medicine", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Product");

                    b.Property<int>("DosageMg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsPrescription")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Medicine");
                });

            modelBuilder.Entity("DatabaseApp.Models.Toy", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Product");

                    b.Property<int>("EngagementRating")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Toy");
                });

            modelBuilder.Entity("DatabaseApp.Models.EdibleToy", b =>
                {
                    b.HasBaseType("DatabaseApp.Models.Toy");

                    b.Property<int>("CalorieCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Softness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Products", t =>
                        {
                            t.Property("CalorieCount")
                                .HasColumnName("EdibleToy_CalorieCount");

                            t.Property("FatCount")
                                .HasColumnName("EdibleToy_FatCount");
                        });

                    b.HasDiscriminator().HasValue("EdibleToy");
                });

            modelBuilder.Entity("DatabaseApp.Models.Employee", b =>
                {
                    b.HasOne("DatabaseApp.Models.SaleTerminal", "AssignedSaleTerminal")
                        .WithOne("AssignedEmployee")
                        .HasForeignKey("DatabaseApp.Models.Employee", "AssignedSaleTerminalId");

                    b.HasOne("DatabaseApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSaleTerminal");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DatabaseApp.Models.PaymentDetails", b =>
                {
                    b.HasOne("DatabaseApp.Models.SaleTerminal", null)
                        .WithMany("CreatedPaymentDetails")
                        .HasForeignKey("SaleTerminalId");
                });

            modelBuilder.Entity("DatabaseApp.Models.Product", b =>
                {
                    b.HasOne("DatabaseApp.Models.PaymentDetails", "PaymentDetails")
                        .WithMany("Products")
                        .HasForeignKey("PaymentDetailsId");

                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("DatabaseApp.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DatabaseApp.Models.PaymentDetails", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DatabaseApp.Models.SaleTerminal", b =>
                {
                    b.Navigation("AssignedEmployee");

                    b.Navigation("CreatedPaymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
